[package]
name = "mk-cleaner"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
tokio = { version = "1.40.0", features = ["full"] }
misskey = { version = "0.2.0", features = ["http-client", "inspect-contents"] }
env_logger = "0.11.5"
log = "0.4.22"